Reverting back default style
cb4ds/periscope pull request #59
Opened 2021-11-01 09:31 UTC by agenius-logesh

https://3.basecamp.com/3775257/buckets/16956142/todos/4270615472

2021-11-03 10:56 UTC, agenius-mohammed-ali requested changes

2021-11-03 10:56 UTC, agenius-mohammed-ali commented on tests/testthat/sample_app/program/global.R
> +
why you need this extra line?

2021-11-03 10:56 UTC, agenius-mohammed-ali commented on tests/testthat/sample_app_both_sidebar/program/global.R
> +
new line?

2021-11-03 10:56 UTC, agenius-mohammed-ali commented on tests/testthat/sample_app_no_sidebar/program/global.R
> +
the extra

2021-11-03 10:56 UTC, agenius-mohammed-ali commented on tests/testthat/sample_app_no_sidebar_no_resetbutton/program/global.R
> +
the extra line?

2021-11-03 10:56 UTC, agenius-mohammed-ali commented on tests/testthat/sample_app_r_sidebar/program/global.R
> +
the extra line

2021-11-03 12:01 UTC, agenius-mohammed-ali approved these changes

2021-12-07 18:52 UTC, cb4ds approved these changes

2021-12-07 18:52 UTC, merged